"""followers

Revision ID: 03407bf52c86
Revises: 40f94f430231
Create Date: 2021-03-09 19:34:49.505335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03407bf52c86'
down_revision = '40f94f430231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
